отдельный скрипт для проверки сессии и форма для добавления аккаунтов
catindev/ms-admin pull request #17
Opened 2017-07-24 05:37 UTC by exoriri

2017-07-25 06:16 UTC, catindev requested changes
Работает вроде ок. Давай допилим страницу аккаунта. Вот картинка https://yadi.sk/i/Z1jc3wCH3LNdar. По ней:
- 1 - переименуй во "Все аккануты" и пусть ведёт на страницу со списком акков (/accounts);
- 2 - Переименуй в "Настройки аккаунта";
- 3 - Отодвинь кнопку от формы;
- 4 - Сделай логику для выхода: если человек жмёт на эту кнопку, то удалить куку и редирект на корень (логику положи в user.js)

2017-07-25 14:19 UTC, exoriri reviewed
Таймаут сделал,чтобы показать прелоад

2017-07-26 10:39 UTC, catindev requested changes
Всё ок. Доработай в скрипт аккаунта чтение id аккаунта из УРЛ

2017-07-26 10:40 UTC, catindev commented
> Таймаут сделал,чтобы показать прелоад

ок. посмотрел. таймаут можно убрать

2017-07-26 12:15 UTC, exoriri commented on static/account.js
> +  const companyId = location.pathname;
чтение id из url

2017-07-26 13:16 UTC, catindev commented on static/account.js
> +  const companyId = location.pathname;
> const companyId = location.pathname;
Выведи в консоль. Проверяй перед тем как пушить ☝️

2017-07-26 13:19 UTC, exoriri commented on static/account.js
> +  const companyId = location.pathname;
accounts/id

2017-07-26 15:07 UTC, catindev commented on static/account.js
> +  const companyId = location.pathname;
Не то. Попробую наглядно, картинкой https://yadi.sk/i/2baXW4v-3LRzpg Так понятнее?

2017-07-26 16:38 UTC, exoriri commented on static/account.js
> +  const companyId = location.pathname;
Не,я понял). Просто почему просто нельзя или это как-то влияет?

2017-07-26 17:34 UTC, exoriri commented on static/account.js
> +  const companyId = location.pathname.replace(/[^0-9]/gim,'');
теперь берет только id. Но все ровно не понял,почему нельзя было сразу /accounts/id передать

2017-07-26 17:41 UTC, exoriri commented on static/account.js
> +  const companyId = location.pathname;
не я понял). Я не понимаю,почему просто нельзя сразу все прочитать и запрос поставить

2017-07-26 17:50 UTC, catindev commented on static/account.js
> +  const companyId = location.pathname.replace(/[^0-9]/gim,'');
> почему нельзя было сразу /accounts/id передать

🤔  да, действительно. Если у нас УРЛ админки такой же как у АПИ, то проще ставить его в запрос целиком. Только переменную переименуй она же теперь не companyId. Молодец, за идею зачёт 👍

2017-07-26 18:14 UTC, exoriri commented on static/account.js
> +  const companyId = location.pathname.replace(/[^0-9]/gim,'');
хорошо

2017-07-26 18:29 UTC, exoriri commented on static/account.js
> +  const url = location.pathname;
изменил companyId на url

2017-08-01 05:41 UTC, merged