фейковый запрос
catindev/ms-admin pull request #2
Opened 2017-07-05 04:33 UTC by exoriri

2017-07-05 05:22 UTC, catindev requested changes
Нужно переделать запрос

2017-07-05 05:22 UTC, catindev commented on js/form.js
> +        "Content-Type": "application/json"
2 одинаковых заголовка

2017-07-05 05:22 UTC, catindev commented on js/form.js
> +function send_request(url,params,server_error,login_error) {
О лишних функциях-обёртках мы говорили в прошлый раз. Вспомни

2017-07-05 05:22 UTC, catindev commented on js/form.js
> +      if (response.status !== 200) {
Это зачем?

2017-07-05 05:22 UTC, catindev commented on js/form.js
> +        let login = data[0]['login'];
Это не должно приходить с сервера

2017-07-05 05:22 UTC, catindev commented on js/form.js
> +        if (login === 'test' && password === '111'){
Эта логика должна быть на сервере

2017-07-05 05:22 UTC, catindev commented on js/form.js
> +    .catch(function (error) {
Ошибки будут приходить сюда

2017-07-06 05:07 UTC, catindev requested changes
Почини формат ответа

2017-07-06 05:07 UTC, catindev commented on js/form.js
> +              response.text().then(function (data){
Не текст. Должен быть json. Конкретно параметр session

2017-07-06 05:33 UTC, catindev requested changes

2017-07-06 05:33 UTC, catindev commented on js/form.js
> +      let params = JSON.stringify({login:input_one,password:input_two});
поправить

2017-07-07 06:52 UTC, exoriri reviewed
добавление ошибок

2017-07-07 06:56 UTC, merged