АПИ для редактирования аккаунта
catindev/ms-admin pull request #26
Opened 2017-08-03 06:01 UTC by exoriri

2017-08-03 06:08 UTC, exoriri commented on static/account.js
> +        });
В случае ошибки выделить поля красным цветом,которые были в массиве fields и показать сообщение между названием аккаунта и формой

2017-08-03 06:35 UTC, catindev commented on static/account.js
> +        });
Давай без костылей с бордером. Используй то, что уже есть в бутстрапе http://getbootstrap.com/css/#forms-control-validation

2017-08-03 06:55 UTC, catindev requested changes
У тебя много где встречается код, где ты какие-то стили меняешь через JS. Научись "видеть" всё это состояниями. Например у тебя есть форма. Её состояния:
- Обычное (человек вводит данные);
- Отправка данных на сервер;
- Ошибка;
- Данные отправлены.

Чем отличаются эти состояния? Как дешевле всего поменять состояние на другое? Так ты смотришь не на то как поменять оформление каких-то элементов, но на форму как на что-то целое. 

Понятен этот подход тебе?

2017-08-03 06:55 UTC, catindev commented on static/accounts.js
> +      companies.map(company => {
зачем здесь map?

2017-08-03 06:55 UTC, catindev commented on static/accounts.js
>        let companies = accounts.items;
у тебя здесь лишняя переменная companies. можно сразу с параметром items  работать.
```
  .then( ({ items }) => ...
```

2017-08-03 06:55 UTC, catindev commented on static/accounts.js
> +      document.body.style.backgroundColor = "rgba(0,0,0,0.6)";
Делай классы в CSS для состояния "Ошибка" и добавляй/убирай их. Инлайном, тем более через JS не нужно делать.

2017-08-03 07:00 UTC, catindev commented on static/account.js
> +      .catch(error => {
Этот обработчик сразу будет перебирать поля для ошибки. Но ошибка может быть и другая, без полей

2017-08-03 07:03 UTC, exoriri commented on static/accounts.js
> +      companies.map(company => {
для того чтобы данные компании добавлять в ссылки (id и название ). Можно и циклом сделать

2017-08-03 07:04 UTC, catindev commented on static/accounts.js
> +      companies.map(company => {
Разберись что к чему https://learn.javascript.ru/array-iteration

2017-08-03 07:11 UTC, exoriri commented on static/accounts.js
> +      companies.map(company => {
map используется для редактирования массива, но именно в этом случае он не будет редактироваться,потому что я просто проверяю данные в company и вставляю в ссылку

2017-08-03 10:04 UTC, exoriri commented on static/account.js
> +      .catch(error => {
Тогда надо заранее до отправки проверку делать?

2017-08-03 10:46 UTC, catindev commented on static/account.js
> +      .catch(error => {
Нет, проверяй код ошибки

2017-08-03 13:33 UTC, exoriri commented on static/account.js
> +          });
проверка кода ошибки и удаление borderColor

2017-08-03 13:33 UTC, exoriri commented on static/account.js
> +      errorBlock.classList.add('show');
Добавление стилей

2017-08-03 13:33 UTC, exoriri commented on static/account.js
>      fieldset.disabled = true;
теперь кнопка становится недоступна вместе с полями,а не отдельно

2017-08-04 05:45 UTC, exoriri commented on static/account.js
> +        alertMessage.classList.add('alert-success');
сообщение при успешном сохранении

2017-08-04 05:45 UTC, exoriri commented on static/account.js
> +    alertMessage.style.display = 'none';
при нажатии на кнопку "сохранить" сообщение исчезает

2017-08-04 09:00 UTC, merged