Accounts
catindev/ms-admin pull request #7
Opened 2017-07-11 05:45 UTC by exoriri

неправильно выводит ошибку. Error: [object Object]

2017-07-11 07:07 UTC, catindev requested changes

2017-07-11 07:07 UTC, catindev commented on static/user.js
> +fetch('server/users.php?'+param,)
Ошибки:
- Неправильно отправляешь сессию. Посмотри в задачу; 
- Непонятная переменная param. https://www.youtube.com/watch?v=z5WkDQVeYU4

2017-07-11 07:07 UTC, catindev commented on static/user.js
> +  if (jsonResponse.status !== 200) throw Error(jsonResponse);
Посмотри как в login.js ошибка обрабатывается и как здесь. Разберись. Отпиши в комменте в чём разница и в чём была ошибка.

2017-07-11 07:07 UTC, catindev commented on static/user.js
> +}())
Не user.js, а accounts.js. На каждую страницу свой файл с js-логикой. Не на каждый запрос.

2017-07-11 08:03 UTC, exoriri commented on static/user.js
> +  if (jsonResponse.status !== 200) throw Error(jsonResponse);
там сразу с выводом сообщения,а тут нет. Просто в задании написано ошибку надо, как json выводить). А так если написать jsonResponse.message тоже работать будет

2017-07-11 08:05 UTC, catindev commented on static/user.js
> +  if (jsonResponse.status !== 200) throw Error(jsonResponse);
Ошибку нужно выводить пользователю. В json она будет с сервера приходить

2017-07-11 08:06 UTC, catindev requested changes

2017-07-11 08:06 UTC, catindev commented on static/user.js
> +document.body.style.backgroundColor='#fff';
Зачем цвет фона страницы ты в js устанавливаешь?

2017-07-12 07:58 UTC, catindev requested changes
Отработать по комментариям

2017-07-12 07:58 UTC, catindev commented on static/accounts.js
> +let session = JSON.stringify(Cookies.get());
Почему Cookies.get()? У куки есть конкретное имя, посмотри в login.js
И зачем JSON.stringify? В куке хранится только маркер сессии

2017-07-12 07:58 UTC, catindev commented on static/accounts.js
> +session = document.cookie;
Зачем 2 раза читать сессию?

2017-07-12 07:58 UTC, catindev commented on static/accounts.js
> +fetch('server/accounts.php?'+session)
Смотри как в задаче описан формат:
` /accounts?user_session={значение}`
и сравни со своим. Разница — у тебя просто в query_string передаётся, а в примере из задачи _в параметр_ в query_string

2017-07-12 07:58 UTC, catindev commented on static/accounts.js
> +  redirect(error,errorBlock);
читал о стрелочных функциях? для одного выражения скобки не нужны и можно вот так:
```
.catch(error => redirect(error,errorBlock))
```

2017-07-12 07:58 UTC, catindev commented on static/accounts.js
> +  setTimeout(() => {window.location.replace('index.html')},1500);
Ну ты злодей :) Это у тебя получилось — "у вас есть 1,5 секунды чтобы прочесть что-то на странице", а затем редирект. Если ошибка системная, то никаких редиректов быть не должно. Если ошибка потому, что сессия протухла, то никаких сообщений об ошибке быть не должно.

2017-07-12 08:44 UTC, exoriri commented on static/accounts.js
> +let session = JSON.stringify(Cookies.get());
Cookies.get() использовал, чтобы получить существующие куки. Cookies.get() возвращает объект сохраненный в куки,поэтому использовал JSON.stringify(). Думал,что надо передавать объект в строковом представлении,так как url-это строка. В login.js написано: Cookies.set('user_sessoin'). Получается все ровно надо использовать Cookies.get(),только добавить еще user_seesion, то есть: Cookies.get().user_session,так?

2017-07-12 08:54 UTC, catindev commented on static/accounts.js
> +let session = JSON.stringify(Cookies.get());
Нет. В login.js написано: 
`Cookies.set('user_session', 'тут_маркер_сессии', { срок_действия })`

Читать в переменную. Чтобы прочитать нужно указать метод-геттер и только название:
`const userSession = Cookies.get('user_session')`

Это АПИ готовой библиотеки работы с куками и как пользоваться (записывать куки и читать) описано в документации к ней.

Не забудь перед запросом проверить — может она пустая и можно ничего не запрашивать, а сразу отправлять вводить логин и пароль.

2017-07-12 08:55 UTC, catindev commented on static/accounts.js
> +let session = JSON.stringify(Cookies.get());
P.S. обрати внимание, у тебя опечатка — **user_sessoin**

2017-07-12 09:18 UTC, exoriri commented on static/accounts.js
> +let session = JSON.stringify(Cookies.get());
ахах,хорошо). Я это же просто в комментах писал,так что ничего страшного

2017-07-12 11:15 UTC, catindev requested changes

2017-07-12 11:15 UTC, catindev commented on static/login.js
> +      window.location.replace('accounts.html')}
Проверяй внимательнее исправления 😉

2017-07-12 11:16 UTC, catindev commented
Не забывай про конфликты

2017-07-12 11:23 UTC, catindev requested changes

2017-07-12 11:23 UTC, catindev commented on static/accounts.js
> +    window.location.replace('index.html');
Здесь у тебя всегда будет редирект не зависимо от того какая ошибка

2017-07-12 11:23 UTC, catindev commented on static/accounts.js
> +    errorBlock.style.block = 'block';
Здесь у тебя никогда не будет редиректа не зависимо от того какая ошибка. Поправь

2017-07-12 11:40 UTC, exoriri commented on static/accounts.js
> +    errorBlock.style.block = 'block';
здесь у меня не будет редайректа, только когда будет любая ошибка,кроме ошибки сессии, так как актуальность сессии проверяется сверху. Разве не так должно быть?

2017-07-13 09:32 UTC, catindev approved these changes

2017-07-13 09:32 UTC, catindev commented on static/accounts.js
> +  //window.location.replace('index.html');
?

2017-07-13 09:32 UTC, merged

2017-07-13 09:34 UTC, exoriri commented on static/accounts.js
> +  //window.location.replace('index.html');
блин,убрал редайрект для теста,и потом забыл удалить комментарий